# Generated by Django 3.2.6 on 2021-08-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
